### PR TITLE
Added Directory Fetching Logic through Github API

### PR DESCRIPTION
**Pull request by shreyash3087**
## Description

Directory Fetching: Added logic to fetch directories from GitHub using Node.js and the GitHub API.
UI Enhancement: Implemented a card-style layout to display directories, with each card featuring a "View Repository" button.

**Note:**

This PR addresses the fetching part only,further improvement in the script and UI can be done as per requirements

## Images - 

screencapture-localhost-3000-2024-08-24-09_17_21

## Additional Context:

N/A

### CODE REVIEW

**Comment by shreyash3087** [comment]
@MastanSayyad instead of obfuscating the github token i made a env file since we were allowed to use nodejs.

Obfuscated code can be decrypted so it was of no use to do that, i have made a simple express server which takes the github token from the env file and fetches the directories through github api

@sanjay-kv can you review the pr please

**Review by sanjay-kv — APPROVED** [review]

**Comment by sanjay-kv** [comment]
done @shreyash3087 

can you publish the link to public.

**Comment by shreyash3087** [comment]
@sanjay-kv i havent deployed it anywhere for now, we can do that after we are done with the whole website, also if anyone want to look at the website they can run it on localhost for now, there is a sample env file which i have provided where anyone can put there github token and remove the ".example" from "env.example" and run the express server on localhost to test the website. I havent provided my github token as we discussed about it with @MastanSayyad in #1135

@MastanSayyad should we make a readme file for other contributors so that they can setup the project easily in there local devices

**Comment by sanjay-kv** [comment]
sure

**Comment by MastanSayyad** [comment]
Hey @sanjay-kv Will this basic template be enough? As you said, we can add the necessary info and style it later (also I have on purpose added some bugs to see who identifies it tho it is easy to locate)

image

image

image

image

**Pull request merged**
