### PR TITLE
added the missing repository links and the homepage takes you to the repos, Added nav bar to the "Contact Us" page

### LINKED ISSUE #1494: 🐞[Bug]: The repositories section lead to a page that says "Page not found"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

image
The page is leads the used nowhere. 

### Expected behavior

Instead, it can lead to the git repos like in the about section. Or since there's an "about page" behaving similarly, we can just remove the entire section and keep the home page to just review all the topics.

### keep this
image

### remove this
image

Please tell  me if i should redirect all the sections to the respective repos or just remove the section.

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### LINKED ISSUE #1498: 💡[Feature]: Improve the Contact Us Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Make the contact us page similar to the other pages. Add the Navigation Bar, Progress Bar and a scroll bar for a better experience. Currently, the page uses the default scrollbar, unlike the other pages. Also, adding a padding on top of the page would reduce the clutter.

### Use Case

1. Improves navigation capabilities of the website.
2. the UI design is uniform
3. Users know how much of the page they have gone through the progress bar.

### Benefits

_No response_

### Add ScreenShots

image

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by avogadroB**
## Description

Made changes to index.html and about.html

#1494 
1. Added the NLP and OpenCV cards to the about us page
2. added all the repositories to the home page where previously there were no repositories

#1498 
4. The contact us page has a navigation bar
5. The contact us page styling matches rest of the website

Fixes #1494 
Fixes #1498 

## Checklist:

- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [X ] My changes generate no new warnings

### CODE REVIEW

**Comment by avogadroB** [comment]
> ## Description
> Made changes to index.html and about.html
> 
> 1. Added the NLP and OpenCV cards to the about us page
> 2. added all the repositories to the home page where previously there were no repositories
> 
> Fixes #1494
> 
> ## Checklist:
> * [X ] My code follows the style guidelines of this project
> * [X ] I have performed a self-review of my own code
> * [X ] I have commented my code, particularly in hard-to-understand areas
> * [X ] I have made corresponding changes to the documentation
> * [X ] My changes generate no new warnings

#1494 page not found

**Comment by avogadroB** [comment]
This PR solves 2 of the issues assigned to me

**Review by sanjay-kv — APPROVED** [review]

**Comment by avogadroB** [comment]
Hey there! even if my pr has been merged, I cant see the changes updated on the website. When can I expect to see them?

**Comment by sanjay-kv** [comment]
is it this PR you can see the score on leaderboard

**Comment by avogadroB** [comment]
yes, I can see this pr on the leaderboard

**Pull request merged**
