### PR TITLE
ADD Diagrams/ Graphics on README

### LINKED ISSUE #1438: 📝[Docs]: ADD Diagrams/ Graphics on README
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Diagrams are absent in the README, which is essential for its attractiveness and completeness.

### Suggested Change

Add Diagrams for enhancement

### Rationale

_No response_

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by alo7lika**
## Description

This pull request adds diagrams and graphics to the README to enhance the documentation and provide a clearer understanding of the project. The inclusion of visual aids aims to improve the user experience by making complex concepts easier to grasp. This change addresses the need for more engaging and informative content as highlighted in issue #1438 

**Motivation and Context:**  
Visual representations can significantly aid in the comprehension of machine learning frameworks, libraries, and software, allowing users to quickly grasp key concepts.

**Dependencies:**  
- `matplotlib` - For creating visualizations.

Fixes #1438

## Type of Change

- [x] Added a new machine learning framework, library, or software.
- [x] Documentation update.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
what are those pictures. its not relevant or not look like our website

**Comment by sanjay-kv** [comment]
can u provide a screen recording of your local run

**Comment by alo7lika** [comment]
Made some changes @sanjay-kv

**Comment by alo7lika** [comment]
> what are those pictures. its not relevant or not look like our website


Made some changes @sanjay-kv
kindly Review it

**Comment by alo7lika** [comment]
> Some more changes requested

Since I'm a beginner, I'm facing issues in removing them, since I don't see any delete option or any option to remove them.

**Comment by alo7lika** [comment]
> > Some more changes requested
> 
> Since I'm a beginner, I'm facing issues in removing them, since I don't see any delete option or any option to remove them.

@sanjay-kv

**Pull request closed without merging**
