### PR TITLE
Create Basic Website Template 

### PR DESCRIPTION
**Pull request by MastanSayyad**
@sanjay-kv 

I have created basic template for the website using HTML CSS 

image

### CODE REVIEW

**Comment by shreyash3087** [comment]
@MastanSayyad instead of putting it in the root folder of the repo maybe make a directory with the name Website and do all the website related work in that directory?

**Comment by MastanSayyad** [comment]
Yeah, I almost forgot thanks for reminding me @shreyash3087

**Comment by shreyash3087** [comment]
image


Also the github api is working i can fetch all the directories using my token,although i wanted to clear out a couple of things, should i use my token for the authorisation, if yes can i obuscate the token so that its not human readable but still works? or do you have any other ideas?

**Comment by MastanSayyad** [comment]
Yeah you can obfuscate the token but I think we can replace your token with @sanjay-kv's one

**Comment by aditya-bhaumik** [comment]
@MastanSayyad 
image

I made some small adjustment to the basic template 

Removed the machine learning text  in the navbar as it was not looking good before also instead of adding the link as a button i have added it in the navbar as the github icon  

Also one thing i noticed in your template was that it was missing a favicon which i have added

**Comment by aditya-bhaumik** [comment]
@MastanSayyad if you like this changes can you please make me collabrator in your fork i will add this changes to the pull request

**Comment by MastanSayyad** [comment]
Hi @aditya-bhaumik, Thanks for making the changes. However, it is just a template to help us initialize the tasks for the team. That's why I kept it quite basic on purpose. The modifications you made were part of the screening's planned tasks. we can do it once the tasks get started.

**Comment by shreyash3087** [comment]
@aditya-bhaumik the frontend part can be adjusted later for the whole page,a proper good design can be implemented since this is just a template,although your changes look good,so i guess it can be added for now.

**Comment by sanjay-kv** [comment]
Awesome collaboration.

**Pull request merged**
