### PR TITLE
Human Dataset Visualization

### PR DESCRIPTION
**Pull request by SOMNATH0904**
## Description

In this Project "Human3.6M_dataset_visualization", Here I will convert the human3.6M dataset from txt file to image from for 10 time steps to predict the 11th step & Similarly I will convert the human3.6M dataset from txt file to skeleton gif data.

Fixes # (issue)

## Type of change

- [yes ] Added a new machine learning frameworks, libraries or software.
- [ ] Documentation update

## Checklist:

- [yes] My code follows the style guidelines of this project
- [yes] I have performed a self-review of my own code
- [yes] I have commented my code, particularly in hard-to-understand areas
- [yes] I have made corresponding changes to the documentation
- [yes] My changes generate no new warnings

### CODE REVIEW

**Comment by sanjay-kv** [comment]
can i get the issue link for this

**Comment by SOMNATH0904** [comment]
> can i get the issue link for this

Actually this is a new project added by me. Is it not possible to add a new ML Project ?

**Comment by sanjay-kv** [comment]
you have to raise issue first on opensource once approved you need to raise PR

**Comment by SOMNATH0904** [comment]
> you have to raise issue first on opensource once approved you need to raise PR

It will come under which issue ? 
Like Add a project issue is not described there ...

**Comment by SOMNATH0904** [comment]
> you have to raise issue first on opensource once approved you need to raise PR

I have added a Issue with #837

**Pull request merged**
