### PR TITLE
Added comments to fetal-health-classification.ipynb for better understanding of the code 

### PR DESCRIPTION
**Pull request by shravya312**
## Description

I want to make project beginner and readers friendly by adding clear and concise comments for improving the understanding of the project.
can u review the pr @sanjay-kv 
#1236 fixed
image
image
image

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]

**Comment by shravya312** [comment]
this issue was a great learning about the project fetal health classification, open source will help us gain knowledge and improve the skills.Thanks for giving an opportunity to work on this issue @sanjay-kv

**Comment by shravya312** [comment]
Thanks for giving an opportunity to work on this issue.It was a great learning

**Comment by sanjay-kv** [comment]
there is more you can do, thanks for contributing.

**Comment by shravya312** [comment]
sure I will check for new issues and contribute

**Pull request merged**
