### PR TITLE
Main

### PR DESCRIPTION
**Pull request by snehas-05**
## Description

Tail Effect: A dynamic, interactive effect that creates a smooth, trailing motion that follows the user's cursor movement across the page, adding a touch of elegance and sophistication to your website's design.
I added this effect to enhance your project/ website.
For better understanding, I have added a separate folder name tail_effect in which I have added my html, css and javascript code necessary for this effect.

I request you to kindly merge it for better user experience
Fixes # (issue)

## Type of change

- [ ✓] Added a new machine learning frameworks, libraries or software.
- [ ] Documentation update

## Checklist:

- [ ✓] My code follows the style guidelines of this project
- [ ✓] I have performed a self-review of my own code
- [ ✓] I have commented my code, particularly in hard-to-understand areas
- [ ✓] I have made corresponding changes to the documentation
- [ ✓] My changes generate no new warnings

### CODE REVIEW

**Comment by sanjay-kv** [comment]
which issue this pr it referes

**Comment by snehas-05** [comment]
issue was feature implementation- adding a tail effect to website

**Review by sanjay-kv — APPROVED** [review]

**Comment by snehas-05** [comment]
Hey @sanjay-kv please provide me with all the required labels. Otherwise my points will not be added and counted.

**Comment by snehas-05** [comment]
Hey @sanjay-kv ?

**Comment by UppuluriKalyani** [comment]
@snehas-05 please mention the issue you solved

**Comment by snehas-05** [comment]
Issue number #1373 
Adding a tail effect for a more engaging website

**Comment by sanjay-kv** [comment]
Hey I might have missed it, I will add for sure .

**Comment by snehas-05** [comment]
Can you please do it as soon as possible?

**Comment by snehas-05** [comment]
Thankyou so much @sanjay-kv

**Pull request merged**
