### PR TITLE
@RadhikaMalpani1702 - Created dedicated RecodeHive Organization Page

### LINKED ISSUE #1157: @RadhikaMalpani1702 - Create dedicated RecodeHive Organization Page
@sanjay-kv I would like to work on this task.

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
Hey @sanjay-kv 

- issue closes #1157 

I have created  a dedicated RecodeHive Organization Page
-  Created a dedicated page for recordhive organization 
-  Added navbar and footer 
-  Added Darkmode
-  Fetched all recodehive projects/Repositories
-  Added like to join the organization  
-  Added Get Involved Section

image

image

### Screen Record: 

https://github.com/user-attachments/assets/806fd31b-a945-4010-b0ad-fc5c4056e555

### CODE REVIEW

**Comment by vansh-codes** [comment]
Hii @RadhikaMalpani1702 
Was just going through your PR and changes and noticed this 👇 
image

You have changed the href='/organization' to '/organization.html'
Actually I have implemented router so the routes has to be handled by the router so that the url looks clean
Can you please change it back to '/organization' and try? or see for changes in the router file and mention the organization.html there correctly! If still theres anything please reach out to me again!

**Comment by vansh-codes** [comment]
> @vansh-codes Is the router working? as I am unable to redirect to the pages, it is showing errors.

Yes @MastanSayyad it was working🥲 I even made the 404 error page for invalid urls
Everything was very fine
Someone might have altered maybe, would check it once I get back on my system in a while after dinner 
Thanks for pointing out!

**Comment by MastanSayyad** [comment]
@vansh-codes Now it's working

**Comment by RadhikaMalpani1702** [comment]
@sanjay-kv and @vansh-codes Done

**Review by sanjay-kv — APPROVED** [review]

**Pull request merged**
