### PR TITLE
Add languages.json file in LLM Copilot Extension for VS Code IDE

### PR DESCRIPTION
**Pull request by Pratik-Tech-Wizard**
## Description

This update introduces the LLM Copilot Extension for Visual Studio Code, enhancing the coding experience by integrating a powerful language model directly within the IDE. The extension provides real-time code suggestions, auto-completion, and documentation assistance, enabling developers to write code more efficiently.

Fixes # (1587)

## Type of change

- [x] Added a new machine learning frameworks, libraries or software.
- [x] Documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

image

### CODE REVIEW

**Comment by Pratik-Tech-Wizard** [comment]
@sanjay-kv Please review and approve an appropriate label.

**Review by sanjay-kv — APPROVED** [review]

**Comment by sanjay-kv** [comment]
can i know more about how does this work. and what is the use case. just curious to know about this
@Pratik-Tech-Wizard

**Comment by Pratik-Tech-Wizard** [comment]
The languages file works like :-
-Language Detection: The tool checks the file type (like .py for Python or .js for JavaScript) to know which programming language you’re using.
-Contextual Suggestions: Based on the detected language, it gives you helpful suggestions. For example, it might recommend useful libraries or show you common coding patterns.
-Integration with Frameworks:  It knows about popular frameworks (like Flask for Python or React for JavaScript) and suggests relevant code snippets or best practices.

Use cases for this are Faster Coding, Learning Tool (it provides guidance and examples while you code), Better Code Quality, Easy Prototyping.

@sanjay-kv Kindly designate an appropriate label

**Comment by Pratik-Tech-Wizard** [comment]
The languages file works like :-
-Language Detection: The tool checks the file type (like .py for Python or .js for JavaScript) to know which programming language you’re using.
-Contextual Suggestions: Based on the detected language, it gives you helpful suggestions. For example, it might recommend useful libraries or show you common coding patterns.
-Integration with Frameworks:  It knows about popular frameworks (like Flask for Python or React for JavaScript) and suggests relevant code snippets or best practices.

Use cases for this are Faster Coding, Learning Tool (it provides guidance and examples while you code), Better Code Quality, Easy Prototyping.

@sanjay-kv Kindly designate an appropriate label

**Pull request merged**
