### PR TITLE
UI fixes.enhancements, readme update, added gitignore

### PR DESCRIPTION
**Pull request by vansh-codes**
Co-authored-by: vansh-codes <vanshchaurasiya1557@gmail.com>
Co-authored-by: sanjay-kv <sanjay.kanakkot@gmail.com>

## Description

**TASKS DONE:**
- added gitignore to ignore node_modules and secret files like .env
- fixed the ui background theme and more minor updates in ui
- enhanced UX by enhancing the "Show/Hide" button feature
- Updated readme for the user to clone easily as many are facing issues in cloning

Fixes # (issue)

## Type of change

- [ ] Added a new machine learning frameworks, libraries or software.
- [ ] Documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by vansh-codes** [comment]
@sanjay-kv Please review

**Review by sanjay-kv — APPROVED** [review]

**Comment by vansh-codes** [comment]
hii @sanjay-kv 
I did the co-authored thing still it didnt came 😢

**Comment by sanjay-kv** [comment]
It takes time, if you see in the commit history both of our photo on one commit message then u did proper . It will reflect in one to two days

**Comment by vansh-codes** [comment]
@sanjay-kv in commit history also both of our photo didnt came, i did properly 😢

**Comment by sanjay-kv** [comment]
Something is missing then watch the video again

**Pull request merged**
