### PR TITLE
Added Emotion_Recognition_from_Audio

### PR DESCRIPTION
**Pull request by ChethanaPotukanam**
## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Added main.ipynb file which contain code for emotion recognition from audio using deep learning.
Added README.md which gives information about code and how to download the dataset.
Added requirements.txt to make it is easy for others

Fixes # (issue) #816 

## Type of change

- [x] Added a new machine learning frameworks, libraries or software.
- [ ] Documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by ChethanaPotukanam** [comment]
@sanjay-kv  please review my PR and let me know if there is any mistake I will rectify it.

**Comment by ChethanaPotukanam** [comment]
@sanjay-kv, why hasn't this PR been merged? Is there any mistake?

**Review by sanjay-kv — APPROVED** [review]

**Comment by sanjay-kv** [comment]
done, i might have missed it

**Comment by ChethanaPotukanam** [comment]
Okay @sanjay-kv

**Pull request merged**
