### PR TITLE
added Book Genre Prediction

### PR DESCRIPTION
**Pull request by Aditijainnn**
## Description

prediction model which will predict genre of the book. 

Fixes # (issue)
#764

## Type of change

- [x] Added a new machine learning frameworks, libraries or software.
- [ ] Documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Aditijainnn** [comment]
@sanjay-kv but you give it level 3

**Comment by sanjay-kv** [comment]
It's alright, anyhow this two has 150 point limitation

**Comment by Aditijainnn** [comment]
> It's alright, anyhow this two has 150 point limitation

But i did'nt get 150 points  from this repo now so i can continue to contribute?

**Comment by sanjay-kv** [comment]
image
you will be this repo

**Pull request merged**
