### PR TITLE
added task by vivek

### PR DESCRIPTION
**Pull request by aditya-bhaumik**
@sanjay-kv

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
image

Fixed: #1154

**Comment by vivekvardhan2810** [comment]
@sanjay-kv, me and @aditya-bhaumik co authored and solved.

**Comment by shreyash3087** [comment]
@vivekvardhan2810 @aditya-bhaumik why is it static? and what does the progress bar mean? "5/10 closed" what?

**Comment by vivekvardhan2810** [comment]
@shreyash3087,

The progress bar means that we can know the status of that particular folder, whereas “5/10 closed” indicates that 5 out of 10 tasks, items, or stages have been completed or resolved.

And we added extra cards so that there are some 50 percent ones also all of the ones in the repo are 100

And Which was not looking good

Sanjay Gave me this task

**Comment by vansh-codes** [comment]
@vivekvardhan2810 @aditya-bhaumik I guess writing `34/34` will work or to give more details `34/34 done`  would also work
There's no need for `34 closed / 34 done`  according to me..
What say @shreyash3087 ??

**Comment by aditya-bhaumik** [comment]
@vansh-codes no it will not look nice

**Comment by vivekvardhan2810** [comment]
@vansh-codes i made according to the image sanjay gave me in issue which assigned to me. So i have added

And there is no need 

image

As It is mentioned total and closed

Lets say you have 40 total issues on that project and there are only 20 done till now, There will be still 20 left, from this we can understand and we know so that it will be more informative

How is your method going to help.

**Comment by vansh-codes** [comment]
okay @aditya-bhaumik @vivekvardhan2810 ✅

**Comment by aditya-bhaumik** [comment]
@shreyash3087 its static because all of the projects are done so all are 10/10 or 20/20 which is 100 percent and i dont think new issues will be added as for the extra cards we added them because all the cards had 100 which was not looking good

**Comment by MastanSayyad** [comment]
@aditya-bhaumik @vivekvardhan2810, you both work on this together as co-authors right? I only see Vivek’s commits with code additions and @aditya-bhaumik’s three deletions of "empty space". Did you discuss the code and collaborate, with Vivek making the actual code changes? Or is this just for the badge purpose?

**Comment by aditya-bhaumik** [comment]
Yes @MastanSayyad

**Comment by aditya-bhaumik** [comment]
@MastanSayyad check the issue once which was assigned to vivek once

**Comment by aditya-bhaumik** [comment]
@MastanSayyad both of us worked on it together should not matter who made the commit

**Comment by MastanSayyad** [comment]
Yeah, no worries! Was just curious as it was static.

**Review by sanjay-kv — APPROVED** [review]

**Pull request merged**
