### PR TITLE
Add New Data Analysis Project : Real-Time Google Play Store Data Analytics Dashboard-Python

### LINKED ISSUE #1241: 💡[Feature]: Add a new project (Real-Time Google Play Store Data Analytics Dashboard - Python) in Data Analysis Repo
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to contribute a feature that adds a real-time data analytics dashboard for Google Play Store apps using Python and Plotly. The dashboard is built using datasets that analyze app ratings, reviews, and downloads, providing interactive visualizations.

### Use Case

This feature will allow users to explore and analyze Google Play Store app trends through an interactive dashboard. It offers visual insights into app performance, user sentiment, and download statistics, aiding in data-driven decision-making.

### Benefits

- Adds a dynamic dashboard for visualizing app data.
- Enhances the repository's data analytics capabilities with Plotly.
- Provides an intuitive tool for users to explore app trends and make market decisions.

### Add ScreenShots

Screenshot 2024-10-04 at 4 28 34 PM

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by sanyadureja**
## Description
Added "Real-Time Google Play Store Data Analytics Dashboard-Python" project under "Data Analysis" folder.

The project includes: 
- Datasets (2 csv files)
- .ipynb file
- README.md (Demo video of the interactive dashboard)

Fixes #1241  (issue)

## Type of change

- [✅] Added a new data analysis project.

## Checklist:

- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have made corresponding changes to the documentation
- [✅] My changes generate no new warnings

### CODE REVIEW

**Comment by sanyadureja** [comment]
@sanjay-kv I've completed the task - fixed #1241 issue by adding the new project. Looking forward to getting my PR accepted and the project merged. Please give your meaningful suggestions.

Thank you !!

**Review by sanjay-kv — APPROVED** [review]
awesome.

**Comment by sanyadureja** [comment]
Thank you so much @sanjay-kv

**Comment by sanyadureja** [comment]
@sanjay-kv please assign labels to me for this at the merged stage as well because this PR is not getting reflected on the leaderboard.

**Comment by sanyadureja** [comment]
@sanjay-kv thank you for doing the needful.

**Pull request merged**
