### PR TITLE
Create README.md for Prediction Models/Advanced House Price Predictions

### LINKED ISSUE #1495: 📝[Docs]:  README.md file missing inside Prediction Models/Advanced House Price Predictions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Add a README.md file to the Prediction Models/Advanced House Price Predictions directory to provide essential information about the project and its usage.

### Suggested Change

Create a comprehensive README.md file that outlines the project overview, features, dataset details, setup instructions, model training steps, evaluation metrics, and contribution guidelines.

### Rationale

This documentation update is crucial for enhancing user understanding and facilitating contributions to the project.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by RB137**
## Description

Added a README.md file for the Prediction Models/Advanced House Price Predictions project, which was missing earlier.

Fixes #1495 

## Type of change

- [ ] Added a new machine learning frameworks, libraries or software.
- [x] Documentation update

image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by RB137** [comment]
Have a look on it and kindly approve my PR,  and please add the gssoc-ext, hacktoberfest, and hacktoberfest-accepted labels.

**Comment by sanjay-kv** [comment]
its already there, for something to work on see pinned issue

**Comment by RB137** [comment]
@sanjay-kv     
There is no README.md file for the Advanced House Price Prediction model, as shown in the screenshot below. I don’t understand why it's being said that the file already exists. I added the file, as reflected in the screenshot attached to my PR. 
Should I recreate my PR for review? 

Current Screenshot: 
image

**Review by sanjay-kv — APPROVED** [review]

**Comment by sanjay-kv** [comment]
you can fix the conflicts

**Pull request closed without merging**
